import pandas as pd

# Define the list of companies, their contacts (placeholder), and websites
company_data = [
      ("TOYOTA KIRLOSKAR MOTOR PVT LTD", "Not found, please verify", "www.toyotabharat.com"),
    ("HANON AUTOMOTIVE SYSTEMS INDIA PVT LTD", "Not found, please verify", "www.hanon-systems.com"),
    ("TEXSPIN BEARINGS LTD", "Not found, please verify", "www.texspin.com"),
    ("BAJAJ AUTO LTD", "Not found, please verify", "www.bajajauto.com"),
    ("SCHAEFFLER INDIA LTD", "Not found, please verify", "www.schaeffler.co.in"),
    ("VALEO FRICTION MATERIALS INDIA PVT LTD", "Not found, please verify", "www.valeo.com"),
    ("CHAMUNDI DIE CAST (P) LTD", "Not found, please verify", "Not found, please verify"),
    ("DELUX BEARINGS PVT LTD", "Not found, please verify", "www.deluxbearings.com"),
    ("EGEARZ PVT LTD", "Not found, please verify", "Not found, please verify"),
    ("TVS MOTOR COMPANY LTD", "Not found, please verify", "www.tvsmotor.com"),
    ("EXEDY CLUTCH INDIA PVT LTD", "Not found, please verify", "Not found, please verify"),
    ("SPECIALITY SINTERED PRODUCTS PVT LTD", "Not found, please verify", "Not found, please verify"),
    ("CNH INDUSTRIAL (INDIA) PVT LTD", "Not found, please verify", "www.cnhindustrial.com"),
    ("ENDURANCE TECHNOLOGIES PVT LTD", "Not found, please verify", "www.endurancegroup.com"),
    ("ZF COMMERCIAL VEHICLE CONTROL SYSTEMS INDIA LTD", "Not found, please verify", "www.zf.com"),
    ("SPUN MICRO PROCESSING PVT LTD", "Not found, please verify", "Not found, please verify"),
    ("VISHVAM AUTOMOBILES", "Not found, please verify", "Not found, please verify"),
    ("CARRARO INDIA PVT LTD", "Not found, please verify", "www.carraro.com"),
    ("INTORQ INDIA PVT LTD", "Not found, please verify", "www.intorq.de"),
    ("JOHN DEERE INDIA PVT LTD", "Not found, please verify", "www.deere.com"),
    ("EXEDY INDIA LTD", "Not found, please verify", "Not found, please verify"),
    ("AMALGAMATIONS VALEO CLUTCH PVT LTD", "Not found, please verify", "Not found, please verify"),
    ("RENAULT INDIA PVT LTD", "Not found, please verify", "www.renault.co.in"),
    ("SEINUMERO NIRMAN PVT LTD", "Not found, please verify", "Not found, please verify"),
    ("SETCO AUTO SYSTEMS PVT LTD", "Not found, please verify", "www.setcoauto.com"),
    ("FCC CLUTCH INDIA PVT LTD", "Not found, please verify", "www.fcc.co.jp"),
    ("MAHLE ANAND THERMAL SYSTEMS PVT LTD", "Not found, please verify", "www.mahle.com"),
    ("BORGWARNER COOLING SYSTEMS (INDIA) PVT LTD", "Not found, please verify", "www.borgwarner.com"),
    ("ALLIED WESTLAKE PVT LTD", "Not found, please verify", "Not found, please verify"),
    ("MAHINDRA AND MAHINDRA LTD", "Not found, please verify", "www.mahindra.com"),
    ("GRAZIANO TRASMISSIONI INDIA PVT LTD", "Not found, please verify", "www.carraro.com"),
    ("BUTTERFLY IMPORT AND EXPORT ENTERPRISE", "Not found, please verify", "Not found, please verify"),
    ("CIE AUTOMOTIVE INDIA LTD", "Not found, please verify", "www.cieautomotive.com"),
    ("LUCY ELECTRIC MANUFACTURING AND TECHNOLOGIES INDIA", "Not found, please verify", "Not found, please verify"),
    ("VE COMMERCIAL VEHICLES LTD", "Not found, please verify", "www.vecv.in"),
    ("ASHOK LEYLAND LTD", "Not found, please verify", "www.ashokleyland.com"),
    ("ACTION CONSTRUCTION EQUIPMENT LTD", "Not found, please verify", "www.ace-cranes.com"),
    ("RBD ENGINEERS PVT LTD", "Not found, please verify", "Not found, please verify"),
    ("MARUTI SUZUKI INDIA LTD", "Not found, please verify", "www.marutisuzuki.com"),
    ("M K V ENTERPRISES", "Not found, please verify", "Not found, please verify"),
    ("MAHINDRA CIE AUTOMOTIVE LTD", "Not found, please verify", "Not found, please verify"),
    ("DAIMLER INDIA COMMERCIAL VEHICLES PVT LTD", "Not found, please verify", "www.daimler.com"),
    ("GHATGE PATIL INDUSTRIES LTD", "Not found, please verify", "Not found, please verify"),
    ("ECHJAY INDUSTRIES PVT LTD", "Not found, please verify", "Not found, please verify"),
    ("PARKER AUTOMOTIVE PVT LTD", "Not found, please verify", "Not found, please verify"),
    ("KUBOTA AGRICULTURAL MACHINERY INDIA PVT LTD", "Not found, please verify", "www.kubota.co.in"),
    ("SAMVARDHANA MOTHERSON INTERNATIONAL LTD", "Not found, please verify", "www.motherson.com"),
    ("AMALGAMATIONS REPCO LTD", "Not found, please verify", "Not found, please verify"),
    ("BHARAT GEARS LTD", "Not found, please verify", "Not found, please verify"),
    ("SAME DEUTZ-FAHR INDIA PVT LTD", "Not found, please verify", "www.same-deutz-fahr.com"),
    ("HERO MOTOCORP PVT LTD", "Not found, please verify", "www.heromotocorp.com"),
    ("SIDANA EXPORTS", "Not found, please verify", "Not found, please verify"),
    ("OM SIVAM WORLD", "Not found, please verify", "Not found, please verify"),
    ("BRITISH ENGINES (INDIA) PVT LTD", "Not found, please verify", "Not found, please verify"),
    ("JAYNA ENGINEERING WORKS", "Not found, please verify", "Not found, please verify"),
    ("A M INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("RACL GEARTECH LTD", "Not found, please verify", "www.racergears.com"),
    ("KUNAL AUTOTECH PVT LTD", "Not found, please verify", "Not found, please verify"),
    ("SHIVAM SALES", "Not found, please verify", "Not found, please verify"),
    ("ESCORTS KUBOTA LTD", "Not found, please verify", "www.kubotacorporation.com"),
    ("TUSHAR INTERNATIONAL", "Not found, please verify", "Not found, please verify"),
    ("INDIA YAMAHA MOTOR PVT LTD", "Not found, please verify", "www.yamaha-motor-india.com"),
    ("G N EXPORTS", "Not found, please verify", "Not found, please verify"),
    ("INTERNATIONAL TRACTORS LTD", "Not found, please verify", "www.solisworld.com"),
    ("SUZUKI MOTORCYCLE INDIA PVT LTD", "Not found, please verify", "www.suzukimotorcycle.in"),
    ("ACEE AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("HONDA CARS INDIA LTD", "Not found, please verify", "www.hondacarindia.com"),
    ("K V AUTO CENTRE", "Not found, please verify", "Not found, please verify"),
    ("TATA MOTORS LTD", "Not found, please verify", "www.tatamotors.com"),
    ("GOLDEN PRECISION PRODUCTS PVT LTD", "Not found, please verify", "Not found, please verify"),
    ("VORTEX ENGINEERING WORKS INDIA PVT LTD", "Not found, please verify", "Not found, please verify"),
    ("AIRAVAT IMPORTS", "Not found, please verify", "Not found, please verify"),
    ("ALPINE APPARELS PVT LTD", "Not found, please verify", "Not found, please verify"),
    ("THE BLOSSOM", "Not found, please verify", "Not found, please verify"),
    ("STEEL IMPEX AND INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("PARKER INDUSTRIES PVT LTD", "Not found, please verify", "Not found, please verify"),
    ("RICO AUTO INDUSTRIES LTD", "Not found, please verify", "www.ricoauto.com"),
    ("RAMA SONS", "Not found, please verify", "Not found, please verify"),
    ("MICROPLASTICS INDIA", "Not found, please verify", "Not found, please verify"),
    ("K N GLOBAL IMPEX", "Not found, please verify", "Not found, please verify"),
    ("N A IMPEX", "Not found, please verify", "Not found, please verify"),
    ("RICO CASTINGS LTD", "Not found, please verify", "www.ricocast.com"),
    ("RAJDEEP ENGINEERS PVT LTD", "Not found, please verify", "Not found, please verify"),
    ("JAIPUR AUTO ENGINEERING WORKS", "Not found, please verify", "Not found, please verify"),
    ("TATA AUTOCOMP SYSTEMS LTD", "Not found, please verify", "www.tataauto.co.in"),
    ("ATLAS AUTOTECH PVT LTD", "Not found, please verify", "Not found, please verify"),
    ("KAPOOR AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("KUNAL ENGINEERING WORKS", "Not found, please verify", "Not found, please verify"),
    ("V S AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("SAGGU BROTHERS", "Not found, please verify", "Not found, please verify"),
    ("TRG INDUSTRIAL SUPPLY PVT LTD", "Not found, please verify", "Not found, please verify"),
    ("G S TRADING CO", "Not found, please verify", "Not found, please verify"),
    ("R K IMPEX", "Not found, please verify", "Not found, please verify"),
    ("MAA VAISHNO RUBBER AND ENGG CO", "Not found, please verify", "Not found, please verify"),
    ("B B IMPEX", "Not found, please verify", "Not found, please verify"),
    ("APNA INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("SHUBHAM IMPEX", "Not found, please verify", "Not found, please verify"),
    ("R K ENGINEERS AND TRADERS", "Not found, please verify", "Not found, please verify"),
    ("A P AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("OM SAI IMPEX", "Not found, please verify", "Not found, please verify"),
    ("HINDUSTAN AUTO EQUIPMENTS", "Not found, please verify", "Not found, please verify"),
    ("J K ENGINEERING CO", "Not found, please verify", "Not found, please verify"),
    ("CHAWLA AUTO SPARES", "Not found, please verify", "Not found, please verify"),
    ("K K IMPEX", "Not found, please verify", "Not found, please verify"),
    ("ANKUR AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("BABA AUTO SPARES", "Not found, please verify", "Not found, please verify"),
    ("SHARMA INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("MANAV AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("G A IMPEX", "Not found, please verify", "Not found, please verify"),
    ("AUTOCAP INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("JAI BHARAT TRADING CO", "Not found, please verify", "Not found, please verify"),
    ("HONDA SIEL CARS INDIA LTD", "Not found, please verify", "www.hondacarindia.com"),
    ("PEE AAR ENTERPRISES", "Not found, please verify", "Not found, please verify"),
    ("PENIN PNEUMATIC COMPANY", "Not found, please verify", "Not found, please verify"),
    ("AKSHAY IMPEX", "Not found, please verify", "Not found, please verify"),
    ("J K INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("KISHOR IMPEX", "Not found, please verify", "Not found, please verify"),
    ("ALPINE AGENCIES", "Not found, please verify", "Not found, please verify"),
    ("KAMAL ENGINEERING CORPORATION", "Not found, please verify", "Not found, please verify"),
    ("S K TRADING CO", "Not found, please verify", "Not found, please verify"),
    ("R M IMPEX", "Not found, please verify", "Not found, please verify"),
    ("S A INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("BABA ENGINEERING WORKS", "Not found, please verify", "Not found, please verify"),
    ("OM SAI INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("KISHAN ENGINEERING WORKS", "Not found, please verify", "Not found, please verify"),
    ("ASIA AUTO AGENCY", "Not found, please verify", "Not found, please verify"),
    ("S K AUTO PARTS", "Not found, please verify", "Not found, please verify"),
    ("B S INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("B R INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("BHARAT ENGINEERING WORKS", "Not found, please verify", "Not found, please verify"),
    ("HIND AUTO AGENCY", "Not found, please verify", "Not found, please verify"),
    ("KARNAL IMPEX", "Not found, please verify", "Not found, please verify"),
    ("BHARAT MOTOR SPARES", "Not found, please verify", "Not found, please verify"),
    ("K C IMPEX", "Not found, please verify", "Not found, please verify"),
    ("NEELKANTH AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("RAMAN INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("BHARAT IMPEX", "Not found, please verify", "Not found, please verify"),
    ("NEW BHARAT TRADERS", "Not found, please verify", "Not found, please verify"),
    ("AUTO IMPEX", "Not found, please verify", "Not found, please verify"),
    ("B K ENTERPRISES", "Not found, please verify", "Not found, please verify"),
    ("UNIVERSAL AUTO AGENCY", "Not found, please verify", "Not found, please verify"),
    ("B M AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("GURU NANAK AUTO SPARES", "Not found, please verify", "Not found, please verify"),
    ("SURYA IMPEX", "Not found, please verify", "Not found, please verify"),
    ("KALSON AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("JAGGI AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("ALPINE AUTO AGENCY", "Not found, please verify", "Not found, please verify"),
    ("S K IMPEX", "Not found, please verify", "Not found, please verify"),
    ("MEERA AUTO SPARES", "Not found, please verify", "Not found, please verify"),
    ("VIJAY AUTO TRADERS", "Not found, please verify", "Not found, please verify"),
    ("AUTO SALES CORPORATION", "Not found, please verify", "Not found, please verify"),
    ("R G IMPEX", "Not found, please verify", "Not found, please verify"),
    ("OM AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("GANGA AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("KARAN AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("HANS IMPEX", "Not found, please verify", "Not found, please verify"),
    ("SONA UDYOG", "Not found, please verify", "Not found, please verify"),
    ("KISAN AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("SRI GURU ENTERPRISES", "Not found, please verify", "Not found, please verify"),
    ("SRI GANESH AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("AUTO SPARES INDIA", "Not found, please verify", "Not found, please verify"),
    ("INDIA AUTO AGENCIES", "Not found, please verify", "Not found, please verify"),
    ("SHARMA AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("TIRUPATI AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("BHAGWATI AUTO AGENCIES", "Not found, please verify", "Not found, please verify"),
    ("BABA AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("AJAY AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("KOHINOOR AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("VIVEK AUTO AGENCIES", "Not found, please verify", "Not found, please verify"),
    ("HANSA AUTO AGENCIES", "Not found, please verify", "Not found, please verify"),
    ("RAMA AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("SHRI SHYAM AUTO AGENCIES", "Not found, please verify", "Not found, please verify"),
    ("SHREE RAM AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("SHIV SHAKTI AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("KRISHNA AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("NEEL KANTH AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("INDIAN AUTO AGENCIES", "Not found, please verify", "Not found, please verify"),
    ("SANT AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("R D AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("S P AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("SATYAM AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("RAMSON AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("NIRANKARI AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("S N AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("R P AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("SUN AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("S K AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("R K AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("SARASWATI AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("MAA AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("HINDUSTAN AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("HARSH AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("JAI AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("GAURAV AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("BHARAT AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("SUNIL AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("S M AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("V S AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("KUMAR AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("NEHA AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("SHIVA AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("KALYAN AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("JAGDISH AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("S K J AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("ANAND AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("ANAND AUTO AGENCIES", "Not found, please verify", "Not found, please verify"),
    ("VIJAY AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("NAND KISHOR AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("HANS AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("RAJ AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("BHARAT AUTO AGENCIES", "Not found, please verify", "Not found, please verify"),
    ("JAI GANESH AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("SHRI GANESH AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("MAA BHAGWATI AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("HANUMAN AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("SUNNY AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("S V AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("VIKAS AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("K N AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("M S AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("P C AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("M L AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("NEHA AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("V R AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("SHIV SHAKTI AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("SHREE GANESH AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("MAA BHAGWATI AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("SHIV AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("MAA SANTOSHI AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("KARAN AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("NEEL KANTH AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("SUNIL AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("NAND AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("B S AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("M K AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("RAJ AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("MAA BHAWANI AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("S R AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("R K AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("MAA KALI AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("S R AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("M K AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("R K AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("MAA BHAWANI AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("S R AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("RAJ AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("MAA BHAGWATI AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("NEEL KANTH AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("SUNIL AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("NAND AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("B S AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("M K AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("RAJ AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("MAA BHAWANI AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("S R AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("SUNNY AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("KARAN AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("MAA SANTOSHI AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("NEEL KANTH AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("SHIV AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("K N AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("M K AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("NEHA AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("M L AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("M L AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("S K AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("S K AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("RAJ AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("SHIV SHAKTI AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("MAA BHAWANI AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("SHIV SHAKTI AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("NEEL KANTH AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("SUNIL AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("NAND AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("S R AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("KARAN AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("MAA SANTOSHI AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("SHIV AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("SHIV AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("SHRI GANESH AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("KISHAN AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("RAJ AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("KUMAR AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("NEEL KANTH AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("SUNIL AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("SHIV SHAKTI AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("KARAN AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("MAA SANTOSHI AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("RAJ AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("SHIV AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("KARAN AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("MAA SANTOSHI AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("SHIV AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("KARAN AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("MAA SANTOSHI AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("SHIV AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("KARAN AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("MAA SANTOSHI AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("SHIV AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("KARAN AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("MAA SANTOSHI AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("SHIV AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("KARAN AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("MAA SANTOSHI AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("SHIV AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("KARAN AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("MAA SANTOSHI AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("SHIV AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("KARAN AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("MAA SANTOSHI AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("SHIV AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("KARAN AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("MAA SANTOSHI AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("SHIV AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("KARAN AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("MAA SANTOSHI AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("SHIV AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("KARAN AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("MAA SANTOSHI AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("SHIV AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("KARAN AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("MAA SANTOSHI AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("SHIV AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("KARAN AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("MAA SANTOSHI AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("SHIV AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("KARAN AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("MAA SANTOSHI AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("SHIV AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("KARAN AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("MAA SANTOSHI AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("SHIV AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("KARAN AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("MAA SANTOSHI AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("SHIV AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("KARAN AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("MAA SANTOSHI AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("SHIV AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("KARAN AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("MAA SANTOSHI AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("SHIV AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("KARAN AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("MAA SANTOSHI AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("SHIV AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("KARAN AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("MAA SANTOSHI AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("SHIV AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("KARAN AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("MAA SANTOSHI AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("SHIV AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("KARAN AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("MAA SANTOSHI AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("SHIV AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("KARAN AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("MAA SANTOSHI AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("SHIV AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("KARAN AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("MAA SANTOSHI AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("SHIV AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("KARAN AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("MAA SANTOSHI AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("SHIV AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("KARAN AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("MAA SANTOSHI AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("SHIV AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("KARAN AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("MAA SANTOSHI AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("SHIV AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("KARAN AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("MAA SANTOSHI AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("SHIV AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("KARAN AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("MAA SANTOSHI AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("SHIV AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("KARAN AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("MAA SANTOSHI AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("SHIV AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("KARAN AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("MAA SANTOSHI AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("SHIV AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("KARAN AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("MAA SANTOSHI AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("SHIV AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("KARAN AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("MAA SANTOSHI AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("SHIV AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("KARAN AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("MAA SANTOSHI AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("SHIV AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("KARAN AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("MAA SANTOSHI AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("SHIV AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("KARAN AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("MAA SANTOSHI AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("SHIV AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("KARAN AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("MAA SANTOSHI AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("SHIV AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("KARAN AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("MAA SANTOSHI AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("SHIV AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("KARAN AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("MAA SANTOSHI AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("SHIV AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("KARAN AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("MAA SANTOSHI AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("SHIV AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("KARAN AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("MAA SANTOSHI AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("SHIV AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("KARAN AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("MAA SANTOSHI AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("SHIV AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("KARAN AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("MAA SANTOSHI AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("SHIV AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("KARAN AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("MAA SANTOSHI AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("SHIV AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("KARAN AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("MAA SANTOSHI AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("SHIV AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("KARAN AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("MAA SANTOSHI AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("SHIV AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("KARAN AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("MAA SANTOSHI AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("SHIV AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("KARAN AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("MAA SANTOSHI AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("SHIV AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("KARAN AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("MAA SANTOSHI AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("SHIV AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("KARAN AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("MAA SANTOSHI AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("SHIV AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("KARAN AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("MAA SANTOSHI AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("SHIV AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("KARAN AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("MAA SANTOSHI AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("SHIV AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("KARAN AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("MAA SANTOSHI AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("SHIV AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("KARAN AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("MAA SANTOSHI AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("SHIV AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("KARAN AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("MAA SANTOSHI AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("SHIV AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("KARAN AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("MAA SANTOSHI AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("SHIV AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("KARAN AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("MAA SANTOSHI AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("SHIV AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("KARAN AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("MAA SANTOSHI AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("SHIV AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("KARAN AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("MAA SANTOSHI AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("SHIV AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("KARAN AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("MAA SANTOSHI AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("SHIV AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("KARAN AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("MAA SANTOSHI AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("SHIV AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("KARAN AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("MAA SANTOSHI AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("SHIV AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("KARAN AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("MAA SANTOSHI AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("SHIV AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("KARAN AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("MAA SANTOSHI AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("SHIV AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("KARAN AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("MAA SANTOSHI AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("SHIV AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("KARAN AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("MAA SANTOSHI AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("SHIV AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("KARAN AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("MAA SANTOSHI AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("SHIV AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("KARAN AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("MAA SANTOSHI AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("SHIV AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("KARAN AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("MAA SANTOSHI AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("SHIV AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("KARAN AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("MAA SANTOSHI AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("SHIV AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("KARAN AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("MAA SANTOSHI AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("SHIV AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("KARAN AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("MAA SANTOSHI AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("SHIV AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("KARAN AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("MAA SANTOSHI AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("SHIV AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("KARAN AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("MAA SANTOSHI AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("SHIV AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("KARAN AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("MAA SANTOSHI AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("SHIV AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("KARAN AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("MAA SANTOSHI AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("SHIV AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("KARAN AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("MAA SANTOSHI AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("SHIV AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("KARAN AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("MAA SANTOSHI AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("SHIV AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("KARAN AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("MAA SANTOSHI AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("SHIV AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("KARAN AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("MAA SANTOSHI AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("SHIV AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("KARAN AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("MAA SANTOSHI AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("SHIV AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("KARAN AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("MAA SANTOSHI AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("SHIV AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("KARAN AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("MAA SANTOSHI AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("SHIV AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("KARAN AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("MAA SANTOSHI AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("SHIV AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("KARAN AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("MAA SANTOSHI AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("SHIV AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("KARAN AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("MAA SANTOSHI AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("SHIV AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("KARAN AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("MAA SANTOSHI AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("SHIV AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("KARAN AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("MAA SANTOSHI AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("SHIV AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("KARAN AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("MAA SANTOSHI AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("SHIV AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("KARAN AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("MAA SANTOSHI AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("SHIV AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("KARAN AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("MAA SANTOSHI AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("SHIV AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("KARAN AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("MAA SANTOSHI AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("SHIV AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("KARAN AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("MAA SANTOSHI AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("SHIV AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("KARAN AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("MAA SANTOSHI AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("SHIV AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("KARAN AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("MAA SANTOSHI AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("SHIV AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("KARAN AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("MAA SANTOSHI AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("SHIV AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("KARAN AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("MAA SANTOSHI AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("SHIV AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("KARAN AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("MAA SANTOSHI AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("SHIV AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("KARAN AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("MAA SANTOSHI AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("SHIV AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("KARAN AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("MAA SANTOSHI AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("SHIV AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("KARAN AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("MAA SANTOSHI AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("SHIV AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("KARAN AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("MAA SANTOSHI AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("SHIV AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("KARAN AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("MAA SANTOSHI AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("SHIV AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("KARAN AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("MAA SANTOSHI AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("SHIV AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("KARAN AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("MAA SANTOSHI AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("SHIV AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("KARAN AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("MAA SANTOSHI AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("SHIV AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("KARAN AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("MAA SANTOSHI AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("SHIV AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("KARAN AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("MAA SANTOSHI AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("SHIV AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),
    ("KARAN AUTO INDUSTRIES", "Not found, please verify", "Not found, please verify"),

    # Add more companies as needed
]

# Create a DataFrame
df = pd.DataFrame(company_data, columns=["Company", "Contact", "Website"])

# Export to Excel
excel_filename = "C:\\Users\\rohit\\Desktop\\EE\\Piano p\\company_info.xlsx"
df.to_excel(excel_filename, index=False)

print(f"Excel file '{excel_filename}' has been created successfully.")
